# Generated by Django 4.2.6 on 2023-10-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserReport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarydata',
            old_name='created_at',
            new_name='upload_date',
        ),
    ]
