# Generated by Django 4.2.6 on 2023-10-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReport', '0003_rename_name_summarydata_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarydata',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='summarydata',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
